### ISSUE TITLE
Datos

### ISSUE THREAD

**Issue by lucasrodes** [juancri/covid19-vaccination#1]
Hi,
I come here from https://github.com/MinCiencia/Datos-COVID19/issues/804, as you mention you are currently releasing a data report on a daily basis. Could you point me to the file? I can't find it.

Thanks!

**Comment by juancri** [comment]
Hi,

Just check the [releases](https://github.com/juancri/covid19-vaccination/releases). Each release includes a csv file with the vaccinations per day.

**Comment by juancri** [comment]
Closing. Feel free to re-open if you have any other questions.
