### ISSUE TITLE
Link estático al ultimo release?

### ISSUE THREAD

**Issue by ivanMSC** [juancri/covid19-vaccination#2]
La direccion del ultimo release parece depender de la fecha en la que se hizo el release. Como llego a este link sin saber la fecha del release? Alguna posibilidad de tener un link estatico?

**Comment by juancri** [comment]
Efectivamente. Estoy haciendo algunos cambios para incluir las series de cada región y voy a aprovechar de dejar un enlace fijo. Probablemente deje el o los archivos de salida en el mismo repositorio como parte del código. Eso permitiría tener un enlace fijo.

Voy a hacer los cambios y dejo un comentario en este issue más tarde.

**Comment by juancri** [comment]
Se ha acualizado el proceso y formato. Puedes encontrar la última versión [aquí](https://raw.githubusercontent.com/juancri/covid19-vaccination/master/output/chile-vaccination.csv).

Más información sobre el formato en [output](https://github.com/juancri/covid19-vaccination/tree/master/output).
