### ISSUE TITLE
Registrar AstraZeneca en chile-vaccination-type.csv

### ISSUE THREAD

**Issue by lucasrodes** [juancri/covid19-vaccination#26]
Buenas,
Según el [dashboard oficial](https://informesdeis.minsal.cl/SASVisualAnalytics/?reportUri=%2Freports%2Freports%2F9037e283-1278-422c-84c4-16e42a7026c8&sectionIndex=0&sso_guest=true&reportViewOnly=true&reportContextBar=false&sas-welcome=false), se está administrando AstraZeneca. Creo que estas dosis no se están contabilizando en el archivo [`chile-vaccination-type.csv`](https://github.com/juancri/covid19-vaccination/blob/master/output/chile-vaccination-type.csv), que es el que usamos en [owid/covid-19-data](github.com/owid/covid-19-data).

Muchas gracias

**Comment by juancri** [comment]
Lo voy a mirar

**Comment by juancri** [comment]
Agregado en el commit https://github.com/juancri/covid19-vaccination/commit/eb2fae75effba7c818bced015293226da2b0888b\

Esperando que el sitio del DEIS vuelva a funcionar para poder probar

**Comment by juancri** [comment]
Confirmado. Ya se actá actualizando.
