### ISSUE TITLE
BUG: Discrepancia en datos

### ISSUE THREAD

**Issue by lucasrodes** [juancri/covid19-vaccination#29]
Buenas @juancri,
Estamos integrando los datos por rango de edades y me di cuenta que el total de dosis administradas en los archivos [chile-vaccination-ages](https://github.com/juancri/covid19-vaccination/blob/master/output/chile-vaccination-ages.csv) y [chile-vaccination](https://github.com/juancri/covid19-vaccination/blob/master/output/chile-vaccination.csv) es diferente. En concreto:

- En `chile-vaccination-ages`: 15,200,840 primeras dosis y 10,676,196 segundas dosis (valores totales)
- En `chile-vaccination`: 10,676,196 primeras dosis y 8,005,987 segundas dosis (valores totales)

Veo que el valor 10,676,196 aparece en metricas distintas en ambos casos.

---
**UPDATE**

Luego de echar un ojo en https://informesdeis.minsal.cl/SASVisualAnalytics/?reportUri=%2Freports%2Freports%2F9037e283-1278-422c-84c4-16e42a7026c8&sectionIndex=1&sso_guest=true&sas-welcome=false creo que se está asignando los campos originales `Poblacion objetivo` y `1o Dosis` a primeras y segundas dosis, respectivamente. Intuyo el formato del dashboard de DEIS cambió.

Gracias de antemano!

**Comment by juancri** [comment]
Cierto. Lo voy a revisar hoy.

**Comment by juancri** [comment]
@lucasrodes se actualizó el proceso de ambos archivos. Puedes re-abrir el issue si todavía hay algún problema. Gracias.
