### ISSUE TITLE
Datos de vacunación

### ISSUE THREAD

**Issue by dna33** [juancri/covid19-vaccination#3]
Hola, estamos trabajando en una integración completa con los datos del DEIS como hemos hecho con otros productos, sin embargo en el interinato nos gustaría usar tu archivo como fuente, para crear los productos estándares en el repo de MinCiencia. ¿Cómo citamos tu trabajo?

Cuéntame, y también si tienes algún reparo.

Saludos, y gracias.

**Comment by lucasrodes** [comment]
Buenas,
Aprovecho para comentar que yo estoy usando tus datos en https://github.com/sociepy/covid19-vaccination-subnational @juancri. Cito tu proyecto en el README, con un link al fichero en cuestión.

Saludos

**Comment by juancri** [comment]
@dna33, @lucasrodes:

Súper, ningún problema. Lo pueden citar como "COVID-19 Vaccination (JC Olivares)". Voy a ponerlo como título también.

Gracias!

**Comment by juancri** [comment]
A proposito, les puede interesar este issue: https://github.com/juancri/covid19-vaccination/issues/4

Si necesitan algún otro formato, siéntanse libre de comentar ahí o crear otro issue.
