### ISSUE TITLE
Única dosis confundida con segunda dosis

### ISSUE THREAD

**Issue by ivanMSC** [juancri/covid19-vaccination#32]
Me parece que los output estan poniendo las vacunas de única dosis como segunda dosis, lo cual no correspondería.
Por ejemplo, en este caso cómo se podría saber qué cantidad de gente tiene una dosis aplicada? Es decir, cómo saber el número obtenido de sumar 1° dosis + única dósis?

**Comment by juancri** [comment]
Es la forma en la cual el DEIS las está publicando. Es posible ver los detalles del fabricante y, por lo tanto, si necesita segunda dosis, en [chile-vaccination-type.csv](https://github.com/juancri/covid19-vaccination/blob/master/output/chile-vaccination-type.csv).

**Comment by ivanMSC** [comment]
Específicamente, viendo el output que es por regiones, chile-vaccination.csv, no está especificada la cantidad de dosis únicas por región, solo primera y segunda, por lo que se confunden las únicas con las segundas.

En el Deis dispone todo esto en detalle en su dashboard.

**Comment by juancri** [comment]
Por ahora, no hay planes para desagregar los datos regionales por fabricante.
