### ISSUE TITLE
Falta CanSino en el Total de segunda dosis del archivo chile-vaccination.csv

### ISSUE THREAD

**Issue by AntoineBraultChile** [juancri/covid19-vaccination#33]
Hola,

Parece que falta CanSino en el Total de segunda dosis del archivo chile-vaccination.csv.

Eso es normal ?

Gracias.

**Comment by juancri** [comment]
@AntoineBraultChile tienes razón. Vienen así los datos desde el DEIS, pero los voy a revisar.

**Comment by juancri** [comment]
Decidí dar de baja el repositorio. La  actualización va a seguir corriendo pero ya no le voy a dar soporte. Recomiendo obtener los datos que se publican en el repo del ministerio de ciencia: https://github.com/MinCiencia/Datos-COVID19
