### ISSUE TITLE
Aviso: Fin del soporte

### ISSUE THREAD

**Issue by juancri** [juancri/covid19-vaccination#34]
Debido a que no tengo mucho tiempo y ha habido demasiados cambios en el sitio del DEIS, decidí dejar de darle soporte al repositorio. Sugiero obtener los datos desde el repo del ministerio de ciencia: https://github.com/MinCiencia/Datos-COVID19

**Comment by AntoineBraultChile** [comment]
Ok gracias por su trabajo !

**Comment by hectorflorescastillo** [comment]
Agradezco tu trabajo, me fue de gran utilidad. Saludos.

**Comment by juancri** [comment]
@hectorflorescastillo me alegro! :D
