### ISSUE TITLE
Formato datos

### ISSUE THREAD

**Issue by lucasrodes** [juancri/covid19-vaccination#4]
Buenas,
He integrado tus [datos](https://github.com/juancri/covid19-vaccination/blob/master/output/chile-vaccination.csv) en mi proyecto sin ningún problema. De todos modos, me preguntaba, si igual no sería interesante conservar el número de columnas constante? Creo que podría facilitar la integración en varios servicios.

En mi caso particular, por ejemplo, despues de procesar tus datos me quedé con un formato parecido a:

```
region,date,location_iso,region_iso,dose_1,dose_2
Aysén,2021-01-23,CL,CL-AI,11564,0
Aysén,2021-01-24,CL,CL-AI,160,0
Aysén,2021-01-25,CL,CL-AI,1454,0
Antofagasta,2021-01-23,CL,CL-AN,6105,0
Antofagasta,2021-01-24,CL,CL-AN,722,697
Antofagasta,2021-01-25,CL,CL-AN,2900,0
...
```

Gracias por tu trabajo!

**Comment by ivanMSC** [comment]
+1 a este issue. El formato unpivot es mas limpio, aunque mas pesado en formato csv por la redundancia.

Sugeriría disponer de las siguientes columnas: Fecha, ISORegion, Dosis, Cantidad.

**Comment by lucasrodes** [comment]
Buen apunte con la ISO, @ivanMSC.

En mi caso añadí las ISOs usando [este fichero](https://github.com/sociepy/covid19-vaccination-subnational/blob/main/scripts/countries/input/ISO_3166_2.csv). Finalmente, trabajo con [este fichero para Chile](https://github.com/sociepy/covid19-vaccination-subnational/blob/main/data/countries/Chile.csv)

**Comment by juancri** [comment]
@lucasrodes, @ivanMSC,

Interesante. Basé el formato actual en el que usa el MinCiencia en [su repositorio](https://github.com/MinCiencia/Datos-COVID19). Por ejemplo, pueden ver [este archivo del producto 3](https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto3/CasosTotalesCumulativo.csv).

Ahora, ellos también tienen otros dos formatos. El más parecido sería [CasosTotalesCumulativo_std.csv](https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto3/CasosTotalesCumulativo_std.csv).

Me parece bien. Creo que puedo generarlo fácilmente y seria un segundo archivo.

¿Es importante el nombre de la columna? Me gustaría mantener la compatibilidad con el formato del MinCiencia y para eso, los nombres serían algo como "Region", "Region ISO", etc. En resumen, incluiría estas columnas:

- Region
- Region ISO
- Fecha
- Dosis 1
- Dosis 2

Gracias por el feedback!

**Comment by lucasrodes** [comment]
Gracias por el trabajo, @juancri 😄  !

> Interesante. Basé el formato actual en el que usa el MinCiencia en su repositorio. Por ejemplo, pueden ver este archivo del producto 3.

> Ahora, ellos también tienen otros dos formatos. El más parecido sería CasosTotalesCumulativo_std.csv.

Gracias por el contexto!

> ¿Es importante el nombre de la columna? Me gustaría mantener la compatibilidad con el formato del MinCiencia y para eso, los nombres serían algo como "Region", "Region ISO", etc. En resumen, incluiría estas columnas:

En cuanto a los nombres, como tu convengas, adaptaré mis scripts a los nombres que tu elijas. Yo, personalmente, suelo usar [snake case](https://www.theserverside.com/definition/Snake-case) (por ejemplo, `dosis_1` en lugar de `dosis 1`), evitando espacios.

En mi caso, uso python, y tengo [este script](https://github.com/sociepy/covid19-vaccination-subnational/blob/main/scripts/countries/batch/chile.py) para canviar el formato en mi proyecto. Igual algo te es util, aunque he visto usas TypeScript.

> Nota: Los valores de dosis sería la diferencia diaria y no un total acumulado como es en el archivo chile-vaccination.csv.

Gotcha! 💪

**Comment by juancri** [comment]
Ahora que el repositorio del MinCiencia tiene [un producto basado en este repositorio](https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto76/) (mientras se integra oficialmente desde el DEIS), me pregunto si realmente es necesario otro formato en este repositorio. Mi sugerencia sería tomarlo desde el archivo [producto76/vacunacion_std.csv](https://github.com/MinCiencia/Datos-COVID19/blob/master/output/producto76/vacunacion_std.csv). Tengo algunas dudas sobre el formato, pero comenté en [este issue](https://github.com/MinCiencia/Datos-COVID19/issues/804).

**Comment by juancri** [comment]
Por ahora, voy a cerrar el issue. Creo que se puede obtener toda la info desde el repo de minciencia. Siéntanse libres de re-abrir el issue si creen que algo extra sea necesario.
