### ISSUE TITLE
Ejecutar el código

### ISSUE THREAD

**Issue by pescap** [juancri/covid19-vaccination#46]
Al correr el código, parece que toda la parte Loading está ok, pero al llegar a la escritura de los datos de `ChileVaccinationsAges` tira un error: `Cannot read properties of undefined (reading 'valueList')`.

**Comment by juancri** [comment]
Actualmente, veo un timeout en la autenticación, pero parece depender de la hora del día en que se corra el proceso (usualmente, el sitio web del DEIS es muuuuy lento).

¿Puedes postear el log completo para poder tener una idea más clara de dónde se cae? Gracias.

**Comment by juancri** [comment]
Pude replicar el problema. Analizando.

**Comment by juancri** [comment]
Parece haber cambiado la respuesta para las consultas de edades, así es que decidí eliminarlas.  Ya está corregido en master.
