### ISSUE TITLE
Nuevo archivo con las dosis por fabricante

### ISSUE THREAD

**Issue by edomt** [juancri/covid19-vaccination#9]
Hola @juancri 

Muchas gracias por poner a disposición estos datos, han sido muy útiles para nuestro trabajo en @owid.

Hoy hemos añadido un nuevo gráfico con las dosis de vacunas desglosadas por fabricante: https://twitter.com/redouad/status/1359199835056967680

Creo que la información relevante para Chile sería la última vista del dashboard del gobierno ("Total país por día"). No tengo ni idea de lo fácil que es importar esto, pero ¿hay alguna forma de que esté disponible en este repo?

**Comment by juancri** [comment]
Perfecto. Estoy intentando comenzar a publicar toda la info que está en el sitio del DEIS. Esperando por #8.

**Comment by juancri** [comment]
El proceso ya está automatizado. Voy a cerrar este issue ya que está cubierta por #6.
